version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm i && npm run dev"
    networks:
      - backend-network
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge
